# -*- coding: utf-8 -*-
"""pop_pyramid_Task.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nlTs9Jc-ShWTbVy7dYiVHHtip2rKAr0S

# Task: Develop a method to cluster countries based on pop pyramids ( Using age_Dataset)

#KMeans Clustering Method
"""

import pandas as pd
from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler
import matplotlib.pyplot as plt
import seaborn as sns

"""##Used age_data.csv and it contains 21 age groups per country for 2021"""

df = pd.read_csv('age_data.csv',low_memory=False)

df = df[['Location','Time', 'AgeGrpStart','PopTotal']]

#Filter for 2021 year
year_to_use = 2021
df = df[df['Time'] == 2021]

df.dropna(subset=['Location','AgeGrpStart','PopTotal'],inplace=True)

df['AgeGrpStart'] = df['AgeGrpStart'].astype(int)
df['PopTotal'] = df['PopTotal'].astype(float)

pivot_df = df.pivot_table(index=['Location'], columns= 'AgeGrpStart', values='PopTotal', fill_value=0)

pivot_df = pivot_df.reindex(columns=sorted(pivot_df.columns),fill_value=0)

pivot_norm = pivot_df.div(pivot_df.sum(axis=1), axis=0)

scaler = StandardScaler()
data_scaled = scaler.fit_transform(pivot_norm)

k = 4
kmeans = KMeans(n_clusters=k, random_state=42)
clusters = kmeans.fit_predict(data_scaled)

pivot_norm['Cluster'] = clusters

print(pivot_norm.head())

for cluster_num in range(k):
  cluster_data = pivot_norm[pivot_norm['Cluster'] == cluster_num].drop(columns='Cluster')
  mean_pyramid = cluster_data.mean()

  plt.figure(figsize=(12,6))
  sns.barplot(x=mean_pyramid.index.astype(str), y=mean_pyramid.values)
  plt.title(f'Average Population Pyramid for cluster {cluster_num}({2021})')
  plt.xlabel('Age Group Start')
  plt.ylabel('Proportion of Population')
  plt.xticks(rotation=45)
  plt.show()

  pivot_norm.reset_index()[['Location', 'Cluster']].to_csv('clustered_countries.csv', index=False)

# PCA 2D scatter plot
from sklearn.decomposition import PCA
pca = PCA(n_components=2)
data_2d = pca.fit_transform(data_scaled)

plt.figure(figsize=(10, 7))
scatter = plt.scatter(data_2d[:, 0], data_2d[:, 1], c=clusters, cmap='tab10' ,alpha =0.7)
plt.title(f'KMeans Clusters of Countries (2021)')
plt.xlabel('PCA 1')
plt.ylabel('PCA 2')
plt.legend(*scatter.legend_elements(), title='Clusters')
plt.show()

